name: "Rerun Old Bot Run (pull_request_target) on review"
description: "This is a hack and requires workflow_run event trigger type"
inputs:
  GITHUB-TOKEN:
    description: |-
      The Github token to be used by this bot when merging, posting comments, or requesting reviewers
    required: true
  WORKFLOW-ID:
    description: |-
      The workflow ID of triggering workflow, this can be accessed via github.event.workflow_run.id
    required: true
  ID-TO-RERUN:
    description: |-
      Every workflow has an ID, and you must include the id here to let this action know which workflow to rerun
    required: true
  EVENT-TYPE:
    description: |-
      The name of the event triggering this workflow that you want to rerun
    required: true

runs:
  using: "composite"
  steps:
    - run: cd ${{github.action_path}} && npm ci && npm run build && EVENT_TYPE=${{inputs.EVENT-TYPE}} GITHUB_TOKEN=${{ inputs.GITHUB-TOKEN }} ID_TO_RERUN=${{ inputs.ID-TO-RERUN }} WORKFLOW_ID=${{ inputs.WORKFLOW-ID }} node build/index.js
      shell: bash
