name: "Auto Merge EIP"
description: "A bot that lints EIP edits, finds common errors, and can auto-merge"
inputs:
  GITHUB-TOKEN:
    description: |-
      The Github token to be used by this bot when merging, posting comments, or requesting reviewers
    required: true
  MERGE_ENABLED:
    description: if true then the bot merge abilities are enabled, otherwise the bot will not merge
    required: false

runs:
  using: "composite"
  steps:
    - run: cd ${{github.action_path}} && yarn install && yarn build && GITHUB_TOKEN=${{ inputs.GITHUB-TOKEN }} MERGE_ENABLED=${{ inputs.MERGE_ENABLED }} node build/src/index.js
      shell: bash
